### PR TITLE
feat/#170 add rules and tests for bitmaps

### PR DESCRIPTION
**Pull request by konki-vienna**
Added some code to check if bitmaps that don't use a layer style have no default styling (such as fills, borders, shadows, inner shadows, blur or colour adjust). If a bitmap layer has a non-default styling, a violation is triggered.
Added tests to cover that.

### CODE REVIEW

**Comment by bomberstudios** [comment]
Thanks a lot for this (and extra karma points for including tests! : )

**Review by bomberstudios — APPROVED** [review]
Looks good & tests pass, approved 🎉

**Comment by jedrichards** [comment]
Looks good to me too! Shall we merge @christianklotz?

**Comment by jedrichards** [comment]
@christianklotz It'd be nice to release this soon, but to do that we'll need to manually add a changeset for this in a quick new PR.

**Pull request merged**
